
package com.viettel.qldtktts.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SmartOfficeService", targetNamespace = "http://webservice.qldtktts.viettel.com/", wsdlLocation = "http://10.58.71.138:8877/SRC_WS_SMART_OFFICE/SmartOfficeService?wsdl")
public class SmartOfficeService_Service
    extends Service
{

    private final static URL SMARTOFFICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SMARTOFFICESERVICE_EXCEPTION;
    private final static QName SMARTOFFICESERVICE_QNAME = new QName("http://webservice.qldtktts.viettel.com/", "SmartOfficeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.58.71.138:8877/SRC_WS_SMART_OFFICE/SmartOfficeService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SMARTOFFICESERVICE_WSDL_LOCATION = url;
        SMARTOFFICESERVICE_EXCEPTION = e;
    }

    public SmartOfficeService_Service() {
        super(__getWsdlLocation(), SMARTOFFICESERVICE_QNAME);
    }

    public SmartOfficeService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SMARTOFFICESERVICE_QNAME, features);
    }

    public SmartOfficeService_Service(URL wsdlLocation) {
        super(wsdlLocation, SMARTOFFICESERVICE_QNAME);
    }

    public SmartOfficeService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SMARTOFFICESERVICE_QNAME, features);
    }

    public SmartOfficeService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SmartOfficeService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SmartOfficeService
     */
    @WebEndpoint(name = "SmartOfficeServicePort")
    public SmartOfficeService getSmartOfficeServicePort() {
        return super.getPort(new QName("http://webservice.qldtktts.viettel.com/", "SmartOfficeServicePort"), SmartOfficeService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SmartOfficeService
     */
    @WebEndpoint(name = "SmartOfficeServicePort")
    public SmartOfficeService getSmartOfficeServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.qldtktts.viettel.com/", "SmartOfficeServicePort"), SmartOfficeService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SMARTOFFICESERVICE_EXCEPTION!= null) {
            throw SMARTOFFICESERVICE_EXCEPTION;
        }
        return SMARTOFFICESERVICE_WSDL_LOCATION;
    }

}
