
package com.viettel.qldtktts.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SmartOfficeService", targetNamespace = "http://webservice.qldtktts.viettel.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SmartOfficeService {


    /**
     * 
     * @param date
     * @param reason
     * @param password
     * @param count
     * @param merEntityId
     * @param type
     * @param userName
     * @return
     *     returns com.viettel.qldtktts.webservice.Kttsbo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateStatusEntity", targetNamespace = "http://webservice.qldtktts.viettel.com/", className = "com.viettel.qldtktts.webservice.UpdateStatusEntity")
    @ResponseWrapper(localName = "updateStatusEntityResponse", targetNamespace = "http://webservice.qldtktts.viettel.com/", className = "com.viettel.qldtktts.webservice.UpdateStatusEntityResponse")
    @Action(input = "http://webservice.qldtktts.viettel.com/SmartOfficeService/updateStatusEntityRequest", output = "http://webservice.qldtktts.viettel.com/SmartOfficeService/updateStatusEntityResponse")
    public Kttsbo updateStatusEntity(
        @WebParam(name = "merEntityId", targetNamespace = "")
        Long merEntityId,
        @WebParam(name = "count", targetNamespace = "")
        Long count,
        @WebParam(name = "date", targetNamespace = "")
        XMLGregorianCalendar date,
        @WebParam(name = "type", targetNamespace = "")
        Long type,
        @WebParam(name = "reason", targetNamespace = "")
        String reason,
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param reason
     * @param password
     * @param idBBBGTSCN
     * @param type
     * @param userName
     * @return
     *     returns com.viettel.qldtktts.webservice.Kttsbo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateTypeInHan", targetNamespace = "http://webservice.qldtktts.viettel.com/", className = "com.viettel.qldtktts.webservice.UpdateTypeInHan")
    @ResponseWrapper(localName = "updateTypeInHanResponse", targetNamespace = "http://webservice.qldtktts.viettel.com/", className = "com.viettel.qldtktts.webservice.UpdateTypeInHanResponse")
    @Action(input = "http://webservice.qldtktts.viettel.com/SmartOfficeService/updateTypeInHanRequest", output = "http://webservice.qldtktts.viettel.com/SmartOfficeService/updateTypeInHanResponse")
    public Kttsbo updateTypeInHan(
        @WebParam(name = "idBBBGTSCN", targetNamespace = "")
        Long idBBBGTSCN,
        @WebParam(name = "reason", targetNamespace = "")
        String reason,
        @WebParam(name = "type", targetNamespace = "")
        Long type,
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param password
     * @param start
     * @param limit
     * @param idBBBGTSCN
     * @param userName
     * @return
     *     returns com.viettel.qldtktts.webservice.Kttsbo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListEntityInHan", targetNamespace = "http://webservice.qldtktts.viettel.com/", className = "com.viettel.qldtktts.webservice.GetListEntityInHan")
    @ResponseWrapper(localName = "getListEntityInHanResponse", targetNamespace = "http://webservice.qldtktts.viettel.com/", className = "com.viettel.qldtktts.webservice.GetListEntityInHanResponse")
    @Action(input = "http://webservice.qldtktts.viettel.com/SmartOfficeService/getListEntityInHanRequest", output = "http://webservice.qldtktts.viettel.com/SmartOfficeService/getListEntityInHanResponse")
    public Kttsbo getListEntityInHan(
        @WebParam(name = "idBBBGTSCN", targetNamespace = "")
        Long idBBBGTSCN,
        @WebParam(name = "start", targetNamespace = "")
        int start,
        @WebParam(name = "limit", targetNamespace = "")
        int limit,
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param password
     * @param employeeId
     * @param type
     * @param keyword
     * @param userName
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "countEntityByUser", targetNamespace = "http://webservice.qldtktts.viettel.com/", className = "com.viettel.qldtktts.webservice.CountEntityByUser")
    @ResponseWrapper(localName = "countEntityByUserResponse", targetNamespace = "http://webservice.qldtktts.viettel.com/", className = "com.viettel.qldtktts.webservice.CountEntityByUserResponse")
    @Action(input = "http://webservice.qldtktts.viettel.com/SmartOfficeService/countEntityByUserRequest", output = "http://webservice.qldtktts.viettel.com/SmartOfficeService/countEntityByUserResponse")
    public int countEntityByUser(
        @WebParam(name = "employeeId", targetNamespace = "")
        String employeeId,
        @WebParam(name = "type", targetNamespace = "")
        Long type,
        @WebParam(name = "keyword", targetNamespace = "")
        String keyword,
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param password
     * @param start
     * @param limit
     * @param employeeId
     * @param type
     * @param keyword
     * @param userName
     * @return
     *     returns com.viettel.qldtktts.webservice.Kttsbo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListEntityByUser", targetNamespace = "http://webservice.qldtktts.viettel.com/", className = "com.viettel.qldtktts.webservice.GetListEntityByUser")
    @ResponseWrapper(localName = "getListEntityByUserResponse", targetNamespace = "http://webservice.qldtktts.viettel.com/", className = "com.viettel.qldtktts.webservice.GetListEntityByUserResponse")
    @Action(input = "http://webservice.qldtktts.viettel.com/SmartOfficeService/getListEntityByUserRequest", output = "http://webservice.qldtktts.viettel.com/SmartOfficeService/getListEntityByUserResponse")
    public Kttsbo getListEntityByUser(
        @WebParam(name = "employeeId", targetNamespace = "")
        String employeeId,
        @WebParam(name = "type", targetNamespace = "")
        Long type,
        @WebParam(name = "start", targetNamespace = "")
        int start,
        @WebParam(name = "limit", targetNamespace = "")
        int limit,
        @WebParam(name = "keyword", targetNamespace = "")
        String keyword,
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param password
     * @param start
     * @param limit
     * @param employeeId
     * @param keyword
     * @param userName
     * @param status
     * @return
     *     returns com.viettel.qldtktts.webservice.Kttsbo
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getListHandoverByUser", targetNamespace = "http://webservice.qldtktts.viettel.com/", className = "com.viettel.qldtktts.webservice.GetListHandoverByUser")
    @ResponseWrapper(localName = "getListHandoverByUserResponse", targetNamespace = "http://webservice.qldtktts.viettel.com/", className = "com.viettel.qldtktts.webservice.GetListHandoverByUserResponse")
    @Action(input = "http://webservice.qldtktts.viettel.com/SmartOfficeService/getListHandoverByUserRequest", output = "http://webservice.qldtktts.viettel.com/SmartOfficeService/getListHandoverByUserResponse")
    public Kttsbo getListHandoverByUser(
        @WebParam(name = "employeeId", targetNamespace = "")
        String employeeId,
        @WebParam(name = "start", targetNamespace = "")
        int start,
        @WebParam(name = "limit", targetNamespace = "")
        int limit,
        @WebParam(name = "status", targetNamespace = "")
        Long status,
        @WebParam(name = "keyword", targetNamespace = "")
        String keyword,
        @WebParam(name = "userName", targetNamespace = "")
        String userName,
        @WebParam(name = "password", targetNamespace = "")
        String password);

}
